using System;
using System.Collections.Generic;
using CaptchaDestroy.Core.ProjectAggregate;

namespace CaptchaDestroy.Web.ApiModels
{
    // ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
    public class CaptchaDTO : CreateCaptchaDTO
    {
        public int Id { get; set; }
        public bool IsSolved { get; set; }
        public string SolutionString { get; set; }

        public static CaptchaDTO FromCaptcha(Captcha captcha)
        {
            return new CaptchaDTO()
            {
                Id = captcha.Id,
                IsSolved = captcha.IsSolved,
                SolutionString = captcha.SolutionString,
                CaptchaUri = captcha.CaptchaUri,
            };
        }
    }

    // Creation DTOs should not include an ID if the ID will be generated by the back end
    public class CreateCaptchaDTO
    {
        public Uri CaptchaUri { get; set; }
    }
}
