// <auto-generated />
using System;
using CaptchaDestroy.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaptchaDestroy.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210725053744_AddPointsToAccountMigration")]
    partial class AddPointsToAccountMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("CaptchaDestroy.Core.ProjectAggregate.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("Points")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecretKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TgId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SecretKey")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("CaptchaDestroy.Core.ProjectAggregate.Captcha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaptchaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaptchaUri")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SolutionString")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Captchas");
                });

            modelBuilder.Entity("CaptchaDestroy.Core.ProjectAggregate.Captcha", b =>
                {
                    b.HasOne("CaptchaDestroy.Core.ProjectAggregate.Account", "Account")
                        .WithMany("Captchas")
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("CaptchaDestroy.Core.ProjectAggregate.Account", b =>
                {
                    b.Navigation("Captchas");
                });
#pragma warning restore 612, 618
        }
    }
}
